### ISSUE TITLE
Error: library puts the Image always in the slide 'p'

### ISSUE THREAD

**Issue by iuiu34** [hairizuanbinnoorazman/rgoogleslides#19]
Hi, if you try to add an image following
https://hairizuan.wordpress.com/2017/05/11/use-case-sending-a-ggplot-graph-into-googleslides/
 the library always paste it in the page ‘p’. (even changing the slideID for another one) 
The cause of this ERROR is in the function ‘aligned_page_element_property’ .The line  adj_page_element_property <- page_element_property("p", height_magnitude = image_height, 

should be

adj_page_element_property <- page_element_property(slide_page_id, height_magnitude = image_height,  
Excellent package!!

**Comment by hairizuanbinnoorazman** [comment]
Currently editing the function to correctly take in the parameters. Thanks for noticing and testing it!

**Comment by hairizuanbinnoorazman** [comment]
@Xavi1234aa Just realized I had a fix in a separate branch - Was adding a whole bunch of functions. Just merged them.

For more information on what is being added:
https://github.com/sparklineanalytics/rgoogleslides/pull/20

Do let me know if this error still persists. Cheers!
