### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by muschellij2** [hairizuanbinnoorazman/rgoogleslides#22]
Hey - great package, like using it.  Is there anything in the works to put this on CRAN?  It seems as though it passes R CMD check all fine, so it wouldn't seem like a huge effort.

Without this, I can't depend on this package for my CRAN packages.
Thoughts?

**Comment by hairizuanbinnoorazman** [comment]
Hi! I'm currently working on checking whether the package is ok to be installed on the windows machine before submitting the CRAN. I'll put the information up here on the progress on this.

Thanks for trying this package out!

**Comment by hairizuanbinnoorazman** [comment]
Update: An initial submission of the package to CRAN is done. Pending approval

**Comment by hairizuanbinnoorazman** [comment]
The package has been successfully submitted to cran.
https://cran.r-project.org/web/packages/rgoogleslides/index.html
